name: Sync DAG-bucket

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sync-gcs-bucket.yaml'
      - 'dags/**'

jobs:
  sync-gcs-bucket:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
    - name: "Set up Cloud SDK"
    - uses: google-github-actions/setup-gcloud@v1
    - name: "Specify GCP project"
      run: "gcloud config set project {{ secrets.PROJECT_ID }}"
    - name: "Sync DAGs to GCS bucket"
      run: gsutil cp -r dags gs://europe-north1-heda-airflow-5fea8b6a-bucket